In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("First Dataset.xlsx")

In [3]:
df.head()

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

In [4]:
print("Shape:", df.shape)

Shape: (61, 17)

In [5]:
print("\nColumns:")
print(df.columns.tolist())

Columns:
['customer_id', 'first_name', 'gender', 'age', 'city', 'province', 'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value', 'total_spending', 'last_purchase_days', 'payment_method', 'device', 'discount_used', 'returned_items', 'satisfaction_score']

In [6]:
print("\nData Types:")
print(df.dtypes)

Data Types:
customer_id             int64
first_name             object
gender                 object
age                   float64
city                   object
province               object
signup_date            object
membership_tier        object
purchase_count          int64
avg_order_value       float64
total_spending        float64
last_purchase_days      int64
payment_method         object
device                 object
discount_used          object
returned_items          int64
satisfaction_score      int64
dtype: object

In [7]:

print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [8]:

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     object
 2   gender              61 non-null     object
 3   age                 60 non-null     float64
 4   city                61 non-null     object
 5   province            61 non-null     object
 6   signup_date         61 non-null     object
 7   membership_tier     61 non-null     object
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     object
 13  device              61 non-null     object
 14  discount_used       61 non-null     object
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.2+ KB

In [10]:
df.describe()

,customer_id,age,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,61.000000,60.000000,61.000000,61.000000,60.000000,61.000000,61.000000,61.00000
mean,1030.229508,45.200000,17.606557,211.435738,3749.667333,196.934426,4.196721,3.00000
std,17.446483,19.167239,10.214824,130.113726,4262.248522,97.892436,2.663454,1.42595
min,1001.000000,19.000000,0.000000,27.630000,0.000000,3.000000,0.000000,1.00000
25%,1015.000000,31.750000,11.000000,108.190000,1167.035000,132.000000,2.000000,2.00000
50%,1030.000000,45.000000,17.000000,161.330000,2188.865000,201.000000,4.000000,3.00000
75%,1045.000000,58.000000,26.000000,323.320000,4692.150000,273.000000,7.000000,4.00000
max,1060.000000,145.000000,35.000000,449.810000,25000.000000,365.000000,8.000000,5.00000

In [11]:
missing = df.isnull().sum()

missing[missing > 0]

age               1
total_spending    1
dtype: int64

In [12]:
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_percent
})

missing_report[missing_report["missing_count"] > 0]

                missing_count  missing_percent
age                         1         1.639344
total_spending              1         1.639344

In [13]:
duplicate_rows = df[df.duplicated(keep=False)]

duplicate_rows

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [14]:
print("Total rows:", len(df))
print("Unique customer IDs:", df["customer_id"].nunique())

Total rows: 61
Unique customer IDs: 60

In [15]:
df[df["customer_id"].duplicated(keep=False)].sort_values("customer_id")

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [16]:
df["signup_date"] = pd.to_datetime(
    df["signup_date"],
    errors="coerce"
)

In [17]:
print(df["signup_date"].dtype)
print("Invalid dates:", df["signup_date"].isna().sum())

datetime64[ns]
Invalid dates: 0

In [18]:
print("Minimum age:", df["age"].min())
print("Maximum age:", df["age"].max())

Minimum age: 19.0
Maximum age: 145.0

In [19]:
df[df["age"] > 100]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [20]:
age_median = df["age"].median()

print("Median age:", age_median)

Median age: 45.0

In [21]:
# اصلاح سن غیرواقعی
df.loc[df["age"] > 100, "age"] = age_median

# پر کردن مقدار خالی age
df["age"] = df["age"].fillna(df["age"].median())

In [22]:
invalid_satisfaction = df[
    ~df["satisfaction_score"].between(1, 5)
]

invalid_satisfaction

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [23]:
categorical_columns = [
    "gender",
    "city",
    "province",
    "membership_tier",
    "payment_method",
    "device",
    "discount_used"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- gender ---
gender
F    35
M    26
Name: count, dtype: int64

--- city ---
city
Tabriz     13
Mashhad    11
Ahvaz       8
Karaj       7
Tehran      6
Shiraz      6
Isfahan     5
Rasht       5
Name: count, dtype: int64

--- province ---
province
East Azerbaijan    13
Khorasan           11
Khuzestan           8
Alborz              7
Tehran              6
Fars                6
Isfahan             5
Gilan               5
Name: count, dtype: int64

--- membership_tier ---
membership_tier
Gold      19
Bronze    18
VIP       16
Silver     8
Name: count, dtype: int64

--- payment_method ---
payment_method
Online Wallet    23
Card             19
Cash             19
Name: count, dtype: int64

--- device ---
device
Android    23
Web        20
iPhone     18
Name: count, dtype: int64

--- discount_used ---
discount_used
No     35
Yes    26
Name: count, dtype: int64

In [24]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (60, 17)

In [25]:
df["calculated_spending"] = (
    df["purchase_count"] * df["avg_order_value"]
)

In [26]:
df["spending_difference"] = (
    df["total_spending"] - df["calculated_spending"]
)

In [27]:
df[
    df["spending_difference"].abs() > 0.01
][[
    "customer_id",
    "purchase_count",
    "avg_order_value",
    "total_spending",
    "calculated_spending",
    "spending_difference"
]]

,customer_id,purchase_count,avg_order_value,total_spending,calculated_spending,spending_difference
29,1030,26,156.89,25000.0,4079.14,20920.86

In [28]:
# اصلاح total_spending اشتباه برای customer_id = 1030

df.loc[
    df["customer_id"] == 1030,
    "total_spending"
] = df.loc[
    df["customer_id"] == 1030,
    "calculated_spending"
].iloc[0]

In [29]:
df[df["total_spending"].isna()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score,calculated_spending,spending_difference
39,1040,Amir,F,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2,1280.44,NaN

In [30]:
df.loc[
    df["total_spending"].isna(),
    "total_spending"
] = (
    df["purchase_count"] *
    df["avg_order_value"]
)

In [31]:
df[df["customer_id"].isin([1030, 1040])][[
    "customer_id",
    "purchase_count",
    "avg_order_value",
    "total_spending",
    "calculated_spending"
]]

,customer_id,purchase_count,avg_order_value,total_spending,calculated_spending
29,1030,26,156.89,4079.14,4079.14
39,1040,34,37.66,1280.44,1280.44

In [32]:
df = df.drop(
    columns=["calculated_spending", "spending_difference"]
)

In [33]:
print("Final shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Final shape: (60, 17)

Missing values:
customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

Duplicate rows:
0

Data types:
customer_id                    int64
first_name                    object
gender                        object
age                          float64
city                          object
province                      object
signup_date           datetime64[ns]
membership_tier               object
purchase_count                 int64
avg_order_value              float64
total_spending               float64
last_purchase_days             int64
payment_method                object
device                        object
discount_used                 object
returned_items                 int64
satisfaction_score             int64
dtype: object

In [34]:
print("\nInvalid ages:")
print(df[~df["age"].between(18, 100)])

print("\nInvalid satisfaction scores:")
print(
    df[~df["satisfaction_score"].between(1, 5)]
)

Invalid ages:
Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

Invalid satisfaction scores:
Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [35]:
df.to_excel(
    "cleaned_dataset.xlsx",
    index=False
)

In [36]:
cleaned_df = pd.read_excel("cleaned_dataset.xlsx")

print(cleaned_df.shape)
cleaned_df.head()

(60, 17)

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

In [37]:
cleaned_df = pd.read_excel("cleaned_dataset.xlsx")

print("Final dataset shape:", cleaned_df.shape)

print("\nTotal missing values:",
      cleaned_df.isnull().sum().sum())

print("\nDuplicate rows:",
      cleaned_df.duplicated().sum())

Final dataset shape: (60, 17)

Total missing values: 0

Duplicate rows: 0