In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_excel(r'F:\StudyBuilt\project1\source\first_dataset.xlsx')

In [3]:
df = data.copy()

In [4]:
df

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Maryam,M,58.0,Ahvaz,Khuzestan,2024-06-11,Bronze,31,436.54,13532.74,82,Cash,iPhone,No,4,4
57,1058,Amir,F,47.0,Tehran,Tehran,2024-09-27,Bronze,5,151.81,759.05,336,Online Wallet,iPhone,No,0,2
58,1059,Ali,F,57.0,Isfahan,Isfahan,2023-09-05,Gold,31,287.05,8898.55,224,Online Wallet,iPhone,Yes,0,5
59,1060,Ali,M,63.0,Tabriz,East Azerbaijan,2021-04-27,Bronze,10,150.18,1501.80,236,Card,Web,Yes,7,3
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [5]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [6]:
del df['customer_id'], df ['first_name'], df['province']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              61 non-null     object
 1   age                 60 non-null     float64
 2   city                61 non-null     object
 3   signup_date         61 non-null     object
 4   membership_tier     61 non-null     object
 5   purchase_count      61 non-null     int64
 6   avg_order_value     61 non-null     float64
 7   total_spending      60 non-null     float64
 8   last_purchase_days  61 non-null     int64
 9   payment_method      61 non-null     object
 10  device              61 non-null     object
 11  discount_used       61 non-null     object
 12  returned_items      61 non-null     int64
 13  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(4), object(7)
memory usage: 6.8+ KB

In [8]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
gender,61,2,F,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,60.0,NaN,NaN,NaN,45.2,19.167239,19.0,31.75,45.0,58.0,145.0
city,61,8,Tabriz,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
signup_date,61,58,2021-11-08,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
membership_tier,61,4,Gold,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_count,61.0,NaN,NaN,NaN,17.606557,10.214824,0.0,11.0,17.0,26.0,35.0
avg_order_value,61.0,NaN,NaN,NaN,211.435738,130.113726,27.63,108.19,161.33,323.32,449.81
total_spending,60.0,NaN,NaN,NaN,3749.667333,4262.248522,0.0,1167.035,2188.865,4692.15,25000.0
last_purchase_days,61.0,NaN,NaN,NaN,196.934426,97.892436,3.0,132.0,201.0,273.0,365.0
payment_method,61,3,Online Wallet,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device,61,3,Android,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discount_used,61,2,No,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
returned_items,61.0,NaN,NaN,NaN,4.196721,2.663454,0.0,2.0,4.0,7.0,8.0
satisfaction_score,61.0,NaN,NaN,NaN,3.0,1.42595,1.0,2.0,3.0,4.0,5.0

### تغییر تایپ ویژگی ها به تایپ استاندارد به صورت امن

In [9]:

df['gender'] = df['gender'].astype('string')

df['age'] = (pd.to_numeric(df['age'],errors='coerce').astype('Int64'))

df['city'] = df['city'].astype('string')

df['signup_date'] = pd.to_datetime(df['signup_date'], format='%Y-%m-%d', errors='coerce')

tier_dtype = pd.CategoricalDtype(categories=['Bronze', 'Silver', 'Gold', 'VIP'], ordered=True)
df['membership_tier'] = df['membership_tier'].astype(tier_dtype) 

df['payment_method'] = df['payment_method'].astype('string')

df['device'] = df['device'].astype('string')

df['discount_used'] = df['discount_used'].astype('string')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              61 non-null     string
 1   age                 60 non-null     Int64
 2   city                61 non-null     string
 3   signup_date         61 non-null     datetime64[ns]
 4   membership_tier     61 non-null     category
 5   purchase_count      61 non-null     int64
 6   avg_order_value     61 non-null     float64
 7   total_spending      60 non-null     float64
 8   last_purchase_days  61 non-null     int64
 9   payment_method      61 non-null     string
 10  device              61 non-null     string
 11  discount_used       61 non-null     string
 12  returned_items      61 non-null     int64
 13  satisfaction_score  61 non-null     int64
dtypes: Int64(1), category(1), datetime64[ns](1), float64(2), int64(4), string(5)
memory usage: 6.6 KB

### داده های تکراری

In [11]:
df.duplicated().sum()

duplicate_rows = df[df.duplicated(keep=False)]                     # مشاهده ردیف های تکراری
display(duplicate_rows)

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,M,35,Tabriz,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,M,35,Tabriz,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [12]:
num_rows =len(df)
df = df.drop_duplicates(keep='last').reset_index(drop=True)
dropped_rows = num_rows - len(df)
print(f' number of deleted rows :', dropped_rows)

 number of deleted rows : 1

### بررسی کلی ویژگی ها

In [13]:
print('-------------------------------------------')
print('1.Value_Count & Cardinality & .......')
for col in df.columns:
    print('-------------------------------------------', '\n')
    print(df[col].value_counts(dropna=False), '\n')
    print(f'cardinality of {col} :', df[col].nunique(dropna=True))
    print('number of value :', df[col].notna().sum())
    print('number of missing value :', df[col].isna().sum())
    print('percentange of missing value :' , df[col].isna().mean()*100)
    print('MINIMUM :', df[col].min())
    print('MAXIMUM : ', df[col].max())
    print(df[col].dtypes, 2*'\n')

    
print('number of missing in each row')
print('------------------------------------')
print(df.isna().sum(axis=1).value_counts()) 

print(2*'\n')
print('number of duplicate row :', df.duplicated().sum())            #تعداد ردیف های تکراری
print('---------------------------','\n')
print('duplicate rows')
print('-----------------')
duplicate_rows = df[df.duplicated(keep=False)]                     # مشاهده ردیف های تکراری
display(duplicate_rows)

-------------------------------------------
1.Value_Count & Cardinality & .......
-------------------------------------------

gender
F    35
M    25
Name: count, dtype: Int64

cardinality of gender : 2
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : F
MAXIMUM :  M
string


-------------------------------------------

age
58      4
23      4
60      4
47      3
25      3
37      3
19      2
32      2
63      2
53      2
45      2
50      2
41      2
61      2
43      2
31      2
39      1
65      1
35      1
57      1
62      1
59      1
48      1
54      1
64      1
26      1
42      1
51      1
28      1
34      1
145     1
22      1
30      1
49      1
<NA>    1
Name: count, dtype: Int64

cardinality of age : 34
number of value : 59
number of missing value : 1
percentange of missing value : 1.6666666666666667
MINIMUM : 19
MAXIMUM :  145
Int64


-------------------------------------------

city
Tabriz     12
Mashhad    11
Ahvaz       8
Karaj       7
Tehran      6
Shiraz      6
Isfahan     5
Rasht       5
Name: count, dtype: Int64

cardinality of city : 8
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : Ahvaz
MAXIMUM :  Tehran
string


-------------------------------------------

signup_date
2023-01-02    2
2021-11-08    2
2025-02-19    1
2024-10-27    1
2022-05-15    1
2022-02-14    1
2024-01-12    1
2022-08-05    1
2022-08-11    1
2021-11-02    1
2023-06-06    1
2021-12-25    1
2021-07-27    1
2024-07-27    1
2022-08-07    1
2024-11-23    1
2022-01-02    1
2024-12-18    1
2022-04-24    1
2023-08-04    1
2025-07-15    1
2022-03-18    1
2021-03-26    1
2024-02-20    1
2025-01-25    1
2024-06-11    1
2024-09-27    1
2023-09-05    1
2021-04-27    1
2021-02-25    1
2024-08-15    1
2022-08-19    1
2024-09-04    1
2023-06-20    1
2021-10-21    1
2022-01-26    1
2025-09-09    1
2024-10-03    1
2021-05-14    1
2022-06-25    1
2021-12-16    1
2023-07-22    1
2021-02-23    1
2021-07-24    1
2022-07-01    1
2025-03-07    1
2021-10-08    1
2024-06-25    1
2022-06-10    1
2021-02-24    1
2024-05-02    1
2025-01-27    1
2021-06-25    1
2022-05-06    1
2024-06-09    1
2021-10-14    1
2023-07-03    1
2022-08-26    1
Name: count, dtype: int64

cardinality of signup_date : 58
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : 2021-02-23 00:00:00
MAXIMUM :  2025-09-09 00:00:00
datetime64[ns]


-------------------------------------------

membership_tier
Gold      19
Bronze    18
VIP       15
Silver     8
Name: count, dtype: int64

cardinality of membership_tier : 4
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : Bronze
MAXIMUM :  VIP
category


-------------------------------------------

purchase_count
23    5
31    5
16    3
18    3
15    3
19    3
12    3
1     3
11    3
9     2
24    2
2     2
17    2
30    2
34    2
3     2
29    2
35    1
5     1
13    1
33    1
7     1
21    1
26    1
4     1
14    1
0     1
6     1
27    1
10    1
Name: count, dtype: int64

cardinality of purchase_count : 30
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : 0
MAXIMUM :  35
int64


-------------------------------------------

avg_order_value
121.53    1
326.47    1
73.00     1
348.13    1
115.60    1
387.68    1
27.63     1
36.87     1
37.66     1
260.33    1
48.06     1
45.00     1
434.98    1
161.33    1
328.23    1
220.87    1
152.26    1
93.06     1
206.60    1
66.53     1
130.12    1
322.53    1
410.16    1
319.38    1
449.81    1
436.54    1
151.81    1
287.05    1
150.18    1
230.05    1
307.67    1
106.43    1
136.17    1
59.46     1
266.15    1
169.54    1
110.53    1
77.15     1
389.58    1
341.63    1
381.13    1
119.16    1
434.50    1
270.91    1
307.91    1
107.98    1
156.89    1
109.70    1
308.72    1
187.17    1
72.62     1
423.43    1
124.24    1
63.67     1
406.03    1
335.41    1
111.97    1
92.68     1
323.32    1
108.19    1
Name: count, dtype: int64

cardinality of avg_order_value : 60
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : 27.63
MAXIMUM :  449.81
float64


-------------------------------------------

total_spending
2066.01     1
3917.64     1
2117.00     1
5918.21     1
1040.40     1
387.68      1
856.53      1
405.57      1
NaN         1
1822.31     1
576.72      1
1035.00     1
14354.34    1
3871.92     1
4923.45     1
5080.01     1
1827.12     1
2140.38     1
6198.00     1
997.95      1
1691.56     1
5805.54     1
3691.44     1
6068.22     1
449.81      1
13532.74    1
759.05      1
8898.55     1
1501.80     1
5521.20     1
4615.05     1
1915.74     1
1497.87     1
1248.66     1
6121.45     1
3899.42     1
3868.55     1
2237.35     1
1168.74     1
11615.42    1
7241.47     1
2264.04     1
11731.50    1
270.91      1
923.73      1
3239.40     1
25000.00    1
1974.60     1
1234.88     1
2994.72     1
1161.92     1
2540.58     1
3851.44     1
0.00        1
812.06      1
3689.51     1
1567.58     1
1482.88     1
646.64      1
3353.89     1
Name: count, dtype: int64

cardinality of total_spending : 59
number of value : 59
number of missing value : 1
percentange of missing value : 1.6666666666666667
MINIMUM : 0.0
MAXIMUM :  25000.0
float64


-------------------------------------------

last_purchase_days
224    3
317    2
205    2
298    2
195    2
16     1
201    1
194    1
126    1
83     1
350    1
54     1
165    1
132    1
229    1
180    1
152    1
141    1
357    1
169    1
80     1
320    1
304    1
221    1
240    1
82     1
336    1
236    1
199    1
112    1
365    1
280    1
22     1
40     1
273    1
232    1
276    1
272    1
117    1
55     1
333    1
135    1
257    1
4      1
139    1
170    1
142    1
160    1
319    1
340    1
261    1
243    1
3      1
97     1
Name: count, dtype: int64

cardinality of last_purchase_days : 54
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : 3
MAXIMUM :  365
int64


-------------------------------------------

payment_method
Online Wallet    23
Cash             19
Card             18
Name: count, dtype: Int64

cardinality of payment_method : 3
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : Card
MAXIMUM :  Online Wallet
string


-------------------------------------------

device
Android    22
Web        20
iPhone     18
Name: count, dtype: Int64

cardinality of device : 3
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : Android
MAXIMUM :  iPhone
string


-------------------------------------------

discount_used
No     34
Yes    26
Name: count, dtype: Int64

cardinality of discount_used : 2
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : No
MAXIMUM :  Yes
string


-------------------------------------------

returned_items
8    9
4    8
7    8
1    7
3    6
5    6
2    6
0    6
6    4
Name: count, dtype: int64

cardinality of returned_items : 9
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : 0
MAXIMUM :  8
int64


-------------------------------------------

satisfaction_score
2    16
4    13
5    12
1    11
3     8
Name: count, dtype: int64

cardinality of satisfaction_score : 5
number of value : 60
number of missing value : 0
percentange of missing value : 0.0
MINIMUM : 1
MAXIMUM :  5
int64


number of missing in each row
------------------------------------
0    58
1     2
Name: count, dtype: int64



number of duplicate row : 0
---------------------------

duplicate rows
-----------------

Empty DataFrame
Columns: [gender, age, city, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

# Checking and Filling Missing Values

### age

In [14]:
print('min :', df['age'].min())
print('max :' ,df['age'].max())
print('average :', df['age'].mean())

min : 19
max : 145
average : 45.3728813559322

In [15]:
# age

df[df['age'] >100]

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,F,145,Karaj,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [16]:
# 1) پیدا کردن ردیف‌های مشکوک
invalid_age_index = df.index[df['age'] > 100]

# 2) ذخیره رکوردها قبل از تغییر
invalid_age_rows_before = df.loc[invalid_age_index].copy()

# 3) تبدیل سن نامعتبر به مقدار گمشده
df.loc[invalid_age_index, 'age'] = np.nan

# 4) دیدن رکوردها بعد از تغییر
invalid_age_rows_after = df.loc[invalid_age_index].copy()

display(invalid_age_rows_before)
display(invalid_age_rows_after)

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,F,145,Karaj,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,F,<NA>,Karaj,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [17]:
# fill by mean

df['age'] = df['age'].fillna(df['age'].mean().round())
df['age'].isna().sum()

np.int64(0)

In [18]:
row = df.loc[9]
print(row)

gender                                  F
age                                    44
city                                Karaj
signup_date           2022-06-25 00:00:00
membership_tier                    Silver
purchase_count                         19
avg_order_value                    381.13
total_spending                    7241.47
last_purchase_days                    276
payment_method              Online Wallet
device                            Android
discount_used                          No
returned_items                          7
satisfaction_score                      1
Name: 9, dtype: object

### total_spending

In [19]:
print('min :', df['total_spending'].min())
print('max :' ,df['total_spending'].max())
print('average :', df['total_spending'].mean())

min : 0.0
max : 25000.0
average : 3756.375423728813

In [20]:
df['exp_spending'] = df['purchase_count'] * df['avg_order_value']
df['diff'] = df['total_spending'] - df['exp_spending']
df[df['diff'] > 0.01]

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score,exp_spending,diff
28,M,60,Mashhad,2025-03-07,VIP,26,156.89,25000.0,340,Cash,Web,Yes,4,4,4079.14,20920.86

In [21]:
# 1) پیدا کردن ردیف‌های مشکوک
invalid_total_index = df.index[df['total_spending'] == 25000]

# 2) ذخیره رکوردها قبل از تغییر
invalid_total_rows_before = df.loc[invalid_total_index].copy()

# 3) تبدیل سن نامعتبر به مقدار گمشده
df.loc[invalid_total_index, 'total_spending'] = np.nan

# 4) دیدن رکوردها بعد از تغییر
invalid_total_rows_after = df.loc[invalid_total_index].copy()

display(invalid_total_rows_before)
display(invalid_total_rows_after)

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score,exp_spending,diff
28,M,60,Mashhad,2025-03-07,VIP,26,156.89,25000.0,340,Cash,Web,Yes,4,4,4079.14,20920.86

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score,exp_spending,diff
28,M,60,Mashhad,2025-03-07,VIP,26,156.89,NaN,340,Cash,Web,Yes,4,4,4079.14,20920.86

In [22]:
df[df['total_spending'].isnull()]

,gender,age,city,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score,exp_spending,diff
28,M,60,Mashhad,2025-03-07,VIP,26,156.89,NaN,340,Cash,Web,Yes,4,4,4079.14,20920.86
38,F,65,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2,1280.44,NaN

In [23]:
# fill by mean
df['total_spending'] = df['total_spending'].fillna(df['total_spending'].mean())

In [24]:
row1 = df.loc[28]
print(row1, '\n')
print('-----------------------------------------------------', '\n')
row2 = df.loc[38]
print(row2)

gender                                  M
age                                    60
city                              Mashhad
signup_date           2025-03-07 00:00:00
membership_tier                       VIP
purchase_count                         26
avg_order_value                    156.89
total_spending                3390.106034
last_purchase_days                    340
payment_method                       Cash
device                                Web
discount_used                         Yes
returned_items                          4
satisfaction_score                      4
exp_spending                      4079.14
diff                             20920.86
Name: 28, dtype: object

-----------------------------------------------------

gender                                  F
age                                    65
city                               Tehran
signup_date           2021-11-02 00:00:00
membership_tier                    Bronze
purchase_count                         34
avg_order_value                     37.66
total_spending                3390.106034
last_purchase_days                    126
payment_method                       Card
device                            Android
discount_used                         Yes
returned_items                          3
satisfaction_score                      2
exp_spending                      1280.44
diff                                  NaN
Name: 38, dtype: object

# FINAL CHECKING

In [25]:
del df['diff'], df['exp_spending']

In [26]:
df.isna().sum()

gender                0
age                   0
city                  0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              60 non-null     string
 1   age                 60 non-null     Int64
 2   city                60 non-null     string
 3   signup_date         60 non-null     datetime64[ns]
 4   membership_tier     60 non-null     category
 5   purchase_count      60 non-null     int64
 6   avg_order_value     60 non-null     float64
 7   total_spending      60 non-null     float64
 8   last_purchase_days  60 non-null     int64
 9   payment_method      60 non-null     string
 10  device              60 non-null     string
 11  discount_used       60 non-null     string
 12  returned_items      60 non-null     int64
 13  satisfaction_score  60 non-null     int64
dtypes: Int64(1), category(1), datetime64[ns](1), float64(2), int64(4), string(5)
memory usage: 6.5 KB

In [31]:
cleaned_dataset_githubusername = df.to_excel('F:\StudyBuilt\project1\data\cleaned_dataset_githubusername.xlsx', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\name\AppData\Local\Temp\ipykernel_9128\3295927520.py:1: SyntaxWarning: invalid escape sequence '\S'
  cleaned_dataset_githubusername = df.to_excel('F:\StudyBuilt\project1\data\cleaned_dataset_githubusername.xlsx', index=False)