# Project 01: Data Cleaning on a Real E-commerce Dataset

## 1. Import Libraries

In [195]:
import pandas as pd

## 2. Load Dataset

In [209]:
df = pd.read_excel("E:/.vscode/Study_build_p01/studybuild-data-cleaning-01/FirstDataset.xlsx")

## 3. Initial Data Inspection

In [197]:
df.shape

(61, 17)

In [198]:
df.columns

Index(['customer_id', 'first_name', 'gender', 'age', 'city', 'province',
       'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value',
       'total_spending', 'last_purchase_days', 'payment_method', 'device',
       'discount_used', 'returned_items', 'satisfaction_score'],
      dtype='object')

In [199]:
df

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Maryam,M,58.0,Ahvaz,Khuzestan,2024-06-11,Bronze,31,436.54,13532.74,82,Cash,iPhone,No,4,4
57,1058,Amir,F,47.0,Tehran,Tehran,2024-09-27,Bronze,5,151.81,759.05,336,Online Wallet,iPhone,No,0,2
58,1059,Ali,F,57.0,Isfahan,Isfahan,2023-09-05,Gold,31,287.05,8898.55,224,Online Wallet,iPhone,Yes,0,5
59,1060,Ali,M,63.0,Tabriz,East Azerbaijan,2021-04-27,Bronze,10,150.18,1501.80,236,Card,Web,Yes,7,3
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [200]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     object
 2   gender              61 non-null     object
 3   age                 60 non-null     float64
 4   city                61 non-null     object
 5   province            61 non-null     object
 6   signup_date         61 non-null     object
 7   membership_tier     61 non-null     object
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     object
 13  device              61 non-null     object
 14  discount_used       61 non-null     object
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.2+ KB

In [201]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
customer_id,61.0,1030.229508,17.446483,1001.00,1015.000,1030.000,1045.00,1060.00
age,60.0,45.200000,19.167239,19.00,31.750,45.000,58.00,145.00
purchase_count,61.0,17.606557,10.214824,0.00,11.000,17.000,26.00,35.00
avg_order_value,61.0,211.435738,130.113726,27.63,108.190,161.330,323.32,449.81
total_spending,60.0,3749.667333,4262.248522,0.00,1167.035,2188.865,4692.15,25000.00
last_purchase_days,61.0,196.934426,97.892436,3.00,132.000,201.000,273.00,365.00
returned_items,61.0,4.196721,2.663454,0.00,2.000,4.000,7.00,8.00
satisfaction_score,61.0,3.000000,1.425950,1.00,2.000,3.000,4.00,5.00

## 4. Detect Duplicate Records

In [210]:
df[df.duplicated()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [211]:
df = df.drop_duplicates()

## 5. Handle Missing Values

In [204]:
df.isna().sum()

customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [212]:
df[df["age"].isna()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
19,1020,Kimia,M,NaN,Isfahan,Isfahan,2024-06-25,Bronze,16,187.17,2994.72,4,Cash,Web,Yes,1,5

In [213]:
df["age"] = df["age"].fillna(df["age"].median())

In [214]:
df[df["total_spending"].isna()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
39,1040,Amir,F,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2

In [215]:
df["total_spending"] = df["total_spending"].fillna(df["total_spending"].median())

In [216]:
df.isna().sum()

customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

## 6. Correct Data Types

In [217]:
df["signup_date"].dtype

dtype('O')

In [218]:
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [219]:
df["signup_date"].dtype

dtype('<M8[ns]')

In [220]:
df["signup_date"].min()

Timestamp('2021-02-23 00:00:00')

In [221]:
df["signup_date"].max()

Timestamp('2025-09-09 00:00:00')

## 7. Detect Invalid Values

In [222]:
df[df["age"]>100]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [223]:
df["age"].median()

np.float64(45.0)

In [224]:
df.loc[df["age"]>100, "age"] = df["age"].median()

In [225]:
df[df["age"]>100]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

## 8. Detect Inconsistent Categorical Values

In [226]:
df["gender"].value_counts()

gender
F    35
M    25
Name: count, dtype: int64

In [227]:
df["city"].value_counts()

city
Tabriz     12
Mashhad    11
Ahvaz       8
Karaj       7
Shiraz      6
Tehran      6
Rasht       5
Isfahan     5
Name: count, dtype: int64

In [228]:
df[["province", "city"]]

           province     city
0            Alborz    Karaj
1            Tehran   Tehran
2              Fars   Shiraz
3          Khorasan  Mashhad
4           Isfahan  Isfahan
5          Khorasan  Mashhad
6             Gilan    Rasht
7             Gilan    Rasht
8            Alborz    Karaj
9            Alborz    Karaj
10           Alborz    Karaj
11         Khorasan  Mashhad
12           Alborz    Karaj
13  East Azerbaijan   Tabriz
14        Khuzestan    Ahvaz
15             Fars   Shiraz
16        Khuzestan    Ahvaz
17             Fars   Shiraz
18             Fars   Shiraz
19          Isfahan  Isfahan
20  East Azerbaijan   Tabriz
21         Khorasan  Mashhad
22         Khorasan  Mashhad
23        Khuzestan    Ahvaz
24         Khorasan  Mashhad
25        Khuzestan    Ahvaz
26          Isfahan  Isfahan
27           Tehran   Tehran
28  East Azerbaijan   Tabriz
29         Khorasan  Mashhad
30           Tehran   Tehran
31          Isfahan  Isfahan
32  East Azerbaijan   Tabriz
33  East Azerbaijan   Tabriz
34  East Azerbaijan   Tabriz
35           Alborz    Karaj
36        Khuzestan    Ahvaz
37         Khorasan  Mashhad
38             Fars   Shiraz
39           Tehran   Tehran
40            Gilan    Rasht
41        Khuzestan    Ahvaz
42        Khuzestan    Ahvaz
43             Fars   Shiraz
44            Gilan    Rasht
45  East Azerbaijan   Tabriz
46  East Azerbaijan   Tabriz
47  East Azerbaijan   Tabriz
48         Khorasan  Mashhad
49         Khorasan  Mashhad
50         Khorasan  Mashhad
51           Alborz    Karaj
52           Tehran   Tehran
53  East Azerbaijan   Tabriz
54            Gilan    Rasht
55  East Azerbaijan   Tabriz
56        Khuzestan    Ahvaz
57           Tehran   Tehran
58          Isfahan  Isfahan
59  East Azerbaijan   Tabriz

In [229]:
df["membership_tier"].value_counts()

membership_tier
Gold      19
Bronze    18
VIP       15
Silver     8
Name: count, dtype: int64

In [230]:
df["payment_method"].value_counts()

payment_method
Online Wallet    23
Cash             19
Card             18
Name: count, dtype: int64

In [231]:
df["device"].value_counts()

device
Android    22
Web        20
iPhone     18
Name: count, dtype: int64

In [232]:
df["discount_used"].value_counts()

discount_used
No     34
Yes    26
Name: count, dtype: int64

In [233]:
df["satisfaction_score"].value_counts(sort=True)

satisfaction_score
2    16
4    13
5    12
1    11
3     8
Name: count, dtype: int64

## 9. Fix Gender Inconsistencies

In [234]:
df.groupby(["first_name"]).nunique()["gender"]

first_name
Ali       2
Amir      2
Arash     2
Kimia     2
Maryam    2
Mina      2
Neda      2
Parsa     2
Reza      2
Sara      1
Sina      2
Zahra     1
Name: gender, dtype: int64

In [235]:
df[df["first_name"]=="Arash"]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,45.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1
11,1012,Arash,F,51.0,Mashhad,Khorasan,2023-07-22,Gold,27,434.50,11731.50,224,Online Wallet,iPhone,Yes,3,2
34,1035,Arash,M,58.0,Tabriz,East Azerbaijan,2022-05-15,Bronze,17,348.13,5918.21,365,Cash,Android,No,5,3
46,1047,Arash,M,37.0,Tabriz,East Azerbaijan,2024-12-18,Gold,23,220.87,5080.01,180,Online Wallet,iPhone,No,4,3

In [236]:
list(df.groupby(["first_name"])["gender"])

[(('Ali',),
  17    F
  22    F
  28    F
  48    F
  58    F
  59    M
  Name: gender, dtype: object),
 (('Amir',),
  5     F
  20    F
  25    M
  37    M
  39    F
  57    F
  Name: gender, dtype: object),
 (('Arash',),
  9     F
  11    F
  34    M
  46    M
  Name: gender, dtype: object),
 (('Kimia',),
  4     M
  8     M
  14    F
  19    M
  26    F
  42    M
  55    M
  Name: gender, dtype: object),
 (('Maryam',),
  33    M
  44    M
  45    F
  56    M
  Name: gender, dtype: object),
 (('Mina',),
  27    F
  43    M
  54    M
  Name: gender, dtype: object),
 (('Neda',),
  10    F
  12    F
  15    F
  18    M
  24    F
  31    F
  32    F
  40    M
  Name: gender, dtype: object),
 (('Parsa',),
  2     F
  16    F
  38    M
  50    F
  Name: gender, dtype: object),
 (('Reza',),
  0     F
  6     F
  7     F
  13    M
  21    M
  49    F
  53    F
  Name: gender, dtype: object),
 (('Sara',),
  51    F
  Name: gender, dtype: object),
 (('Sina',),
  1     M
  3     F
  23    F
  29    M
  35    F
  41    F
  47    F
  52    M
  Name: gender, dtype: object),
 (('Zahra',),
  30    M
  36    M
  Name: gender, dtype: object)]

In [237]:
correct_gender = {
    "Ali"    : "M",
    "Amir"   : "M",
    "Arash"  : "M",
    "Kimia"  : "F",
    "Maryam" : "F",
    "Mina"   : "F",
    "Neda"   : "F",
    "Parsa"  : "M",
    "Reza"   : "M",
    "Sara"   : "F",
    "Sina"   : "M",
    "Zahra"  : "F" 
}
df["gender"] = df["first_name"].map(correct_gender)

In [238]:
df.groupby(["first_name"]).nunique()["gender"]

first_name
Ali       1
Amir      1
Arash     1
Kimia     1
Maryam    1
Mina      1
Neda      1
Parsa     1
Reza      1
Sara      1
Sina      1
Zahra     1
Name: gender, dtype: int64

In [239]:
df.head()

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,M,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,M,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,M,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,F,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

## 10. Validate Business Rules

In [240]:
df[df["purchase_count"] < df["returned_items"]]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
7,1008,Reza,M,23.0,Rasht,Gilan,2024-10-03,VIP,3,389.58,1168.74,195,Online Wallet,iPhone,No,8,1
14,1015,Kimia,F,47.0,Ahvaz,Khuzestan,2021-07-24,Gold,3,307.91,923.73,55,Card,Android,Yes,8,4
23,1024,Sina,M,53.0,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.00,298,Online Wallet,Android,No,2,1
28,1029,Ali,M,34.0,Tabriz,East Azerbaijan,2023-07-03,Gold,2,323.32,646.64,319,Cash,Web,Yes,4,5
36,1037,Zahra,F,42.0,Ahvaz,Khuzestan,2024-01-12,Gold,1,387.68,387.68,199,Cash,Web,Yes,7,2
55,1056,Kimia,F,61.0,Tabriz,East Azerbaijan,2025-01-25,Silver,1,449.81,449.81,240,Online Wallet,Web,No,4,2

In [241]:
df.loc[df["purchase_count"] < df["returned_items"], "returned_items"] = df["purchase_count"]

In [242]:
df[df["purchase_count"] < df["returned_items"]]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [243]:
df[df["total_spending"] <= 0]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
23,1024,Sina,M,53.0,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.0,298,Online Wallet,Android,No,0,1

In [244]:
ts = round((df["purchase_count"] * df["avg_order_value"]), 2)
df[ts != df["total_spending"]]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
29,1030,Sina,M,60.0,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.00,340,Cash,Web,Yes,4,4
39,1040,Amir,M,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,2140.38,126,Card,Android,Yes,3,2

In [245]:
ts.loc[29]

np.float64(4079.14)

In [246]:
ts.loc[39]

np.float64(1280.44)

## 11.Save Cleaned Dataset

In [249]:
df.to_excel("../data/cleaned_dataset_maralfarahmandfar.xlsx", index=False)