In [2]:
# Project 01
## Data Cleaning on an E-commerce Dataset

Author: Ali Khanbeigi

Objective:
Cleaning and preparing a raw e-commerce dataset for future analysis.

SyntaxError: invalid syntax (1771130155.py, line 4)

In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
df = pd.read_excel("D:\projects\project-01-data-cleaning\data\First Dataset.xlsx")

In [5]:
df.head()

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

In [6]:
df.shape

(61, 17)

In [7]:
df.columns

Index(['customer_id', 'first_name', 'gender', 'age', 'city', 'province',
       'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value',
       'total_spending', 'last_purchase_days', 'payment_method', 'device',
       'discount_used', 'returned_items', 'satisfaction_score'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     object
 2   gender              61 non-null     object
 3   age                 60 non-null     float64
 4   city                61 non-null     object
 5   province            61 non-null     object
 6   signup_date         61 non-null     object
 7   membership_tier     61 non-null     object
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     object
 13  device              61 non-null     object
 14  discount_used       61 non-null     object
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.2+ KB

In [8]:
df.describe()

,customer_id,age,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,61.000000,60.000000,61.000000,61.000000,60.000000,61.000000,61.000000,61.00000
mean,1030.229508,45.200000,17.606557,211.435738,3749.667333,196.934426,4.196721,3.00000
std,17.446483,19.167239,10.214824,130.113726,4262.248522,97.892436,2.663454,1.42595
min,1001.000000,19.000000,0.000000,27.630000,0.000000,3.000000,0.000000,1.00000
25%,1015.000000,31.750000,11.000000,108.190000,1167.035000,132.000000,2.000000,2.00000
50%,1030.000000,45.000000,17.000000,161.330000,2188.865000,201.000000,4.000000,3.00000
75%,1045.000000,58.000000,26.000000,323.320000,4692.150000,273.000000,7.000000,4.00000
max,1060.000000,145.000000,35.000000,449.810000,25000.000000,365.000000,8.000000,5.00000

In [9]:
df.describe(include='object')

,first_name,gender,city,province,signup_date,membership_tier,payment_method,device,discount_used
count,61,61,61,61,61,61,61,61,61
unique,12,2,8,8,58,4,3,3,2
top,Reza,F,Tabriz,East Azerbaijan,2021-11-08,Gold,Online Wallet,Android,No
freq,8,35,13,13,2,19,23,23,35

In [21]:
# missing value detection
df.isnull().sum()

customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [22]:
# % Missing Value
(df.isnull().sum() / len(df)) * 100

customer_id           0.000000
first_name            0.000000
gender                0.000000
age                   1.666667
city                  0.000000
province              0.000000
signup_date           0.000000
membership_tier       0.000000
purchase_count        0.000000
avg_order_value       0.000000
total_spending        1.666667
last_purchase_days    0.000000
payment_method        0.000000
device                0.000000
discount_used         0.000000
returned_items        0.000000
satisfaction_score    0.000000
dtype: float64

In [23]:
# checking duplicated records 
df.duplicated().sum()

np.int64(0)

In [24]:
# show duplicated records
df[df.duplicated()]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [13]:
df[df.isnull().any(axis=1)]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
19,1020,Kimia,M,NaN,Isfahan,Isfahan,2024-06-25,Bronze,16,187.17,2994.72,4,Cash,Web,Yes,1,5
39,1040,Amir,F,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2

In [14]:
df[df.duplicated(keep=False)]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [28]:
# removing duplicated records
df.drop_duplicates(inplace=True)

In [20]:
df.duplicated().sum()

np.int64(0)

In [29]:
# filling missing value of age by median
df["age"] = df["age"].fillna(df["age"].median())

In [31]:
# filling missing  value of total_spending
df["total_spending"] = df["total_spending"].fillna(
    df["purchase_count"] * df["avg_order_value"]
)

In [32]:
df.isnull().sum()

customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [42]:
#checking outlier
df[df["age"] > 100]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [43]:
# drop value of outlier
df.loc[df["age"] > 100, "age"] = np.nan

In [44]:
df["age"] = df["age"].fillna(df["age"].median())

In [45]:
df[df["customer_id"]==1010]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,45.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [38]:
df[df["purchase_count"] == 0]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
23,1024,Sina,F,53.0,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.0,298,Online Wallet,Android,No,2,1

In [39]:
df[
    (df["purchase_count"] == 0) &
    (df["avg_order_value"] > 0)
]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
23,1024,Sina,F,53.0,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.0,298,Online Wallet,Android,No,2,1

In [40]:
df[df["total_spending"] == 0]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
23,1024,Sina,F,53.0,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.0,298,Online Wallet,Android,No,2,1

In [41]:
df[
    (df["satisfaction_score"] < 1) |
    (df["satisfaction_score"] > 5)
]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [53]:
df["gender"].value_counts()

gender
F    35
M    25
Name: count, dtype: int64

In [47]:
df["city"].unique()

array(['Karaj', 'Tehran', 'Shiraz', 'Mashhad', 'Isfahan', 'Rasht',
       'Tabriz', 'Ahvaz'], dtype=object)

In [48]:
df["province"].unique()

array(['Alborz', 'Tehran', 'Fars', 'Khorasan', 'Isfahan', 'Gilan',
       'East Azerbaijan', 'Khuzestan'], dtype=object)

In [49]:
df["membership_tier"].unique()

array(['VIP', 'Gold', 'Silver', 'Bronze'], dtype=object)

In [50]:
df["payment_method"].unique()

array(['Card', 'Online Wallet', 'Cash'], dtype=object)

In [52]:
df["device"].value_counts()

device
Android    22
Web        20
iPhone     18
Name: count, dtype: int64

In [54]:
df.groupby(["first_name", "gender"]).size().sort_index()

first_name  gender
Ali         F         5
            M         1
Amir        F         4
            M         2
Arash       F         2
            M         2
Kimia       F         2
            M         5
Maryam      F         1
            M         3
Mina        F         1
            M         2
Neda        F         6
            M         2
Parsa       F         3
            M         1
Reza        F         5
            M         2
Sara        F         1
Sina        F         5
            M         3
Zahra       M         2
dtype: int64

In [55]:
male_names = [
    "Reza",
    "Ali",
    "Amir",
    "Sina",
    "Arash",
    "Parsa"
]

df.loc[df["first_name"].isin(male_names), "gender"] = "M"

In [56]:
female_names = [
    "Sara",
    "Maryam",
    "Kimia",
    "Mina",
    "Zahra",
    "Neda"
]

df.loc[df["first_name"].isin(female_names), "gender"] = "F"

In [57]:
df.groupby(["first_name", "gender"]).size().sort_index()

first_name  gender
Ali         M         6
Amir        M         6
Arash       M         4
Kimia       F         7
Maryam      F         4
Mina        F         3
Neda        F         8
Parsa       M         4
Reza        M         7
Sara        F         1
Sina        M         8
Zahra       F         2
dtype: int64

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         60 non-null     int64
 1   first_name          60 non-null     object
 2   gender              60 non-null     object
 3   age                 60 non-null     float64
 4   city                60 non-null     object
 5   province            60 non-null     object
 6   signup_date         60 non-null     object
 7   membership_tier     60 non-null     object
 8   purchase_count      60 non-null     int64
 9   avg_order_value     60 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  60 non-null     int64
 12  payment_method      60 non-null     object
 13  device              60 non-null     object
 14  discount_used       60 non-null     object
 15  returned_items      60 non-null     int64
 16  satisfaction_score  60 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.4+ KB

In [59]:
df.isnull().sum()

customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [60]:
df.duplicated().sum()

np.int64(0)

In [61]:
df.describe()

,customer_id,age,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,1030.500000,43.700000,17.383333,213.156500,3715.109833,198.600000,4.183333,2.983333
std,17.464249,13.946994,10.149880,130.509923,4273.901437,97.843043,2.683861,1.431979
min,1001.000000,19.000000,0.000000,27.630000,0.000000,3.000000,0.000000,1.000000
25%,1015.750000,31.750000,10.750000,108.137500,1167.035000,134.250000,2.000000,2.000000
50%,1030.500000,45.000000,17.000000,165.435000,2128.690000,203.000000,4.000000,3.000000
75%,1045.250000,58.000000,24.500000,324.107500,4692.150000,273.750000,7.000000,4.000000
max,1060.000000,65.000000,35.000000,449.810000,25000.000000,365.000000,8.000000,5.000000

In [62]:
df.to_excel("cleaned_dataset.xlsx", index=False)

In [ ]:
## Final Summary

### Data Cleaning Tasks Performed

- Removed duplicate records.
- Handled missing values in age using the median.
- Recalculated missing values in total_spending.
- Corrected invalid age values (>100).
- Reviewed inconsistent records.
- Standardized categorical values.
- Corrected intentionally incorrect gender values for educational purposes.
- Exported the cleaned dataset.