In [5]:
import pandas as pd
import numpy as np
path = r"G:\Forough's Folders\StudyBuild\Project 01\First Dataset.xlsx"
df = pd.read_excel(path)
print(df.shape)
#Understanding the dataset

(61, 17)

In [7]:
df.columns
#Column names
df.head()
#The first few rows

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

In [10]:
df.tail()
#The last few rows

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
56,1057,Maryam,M,58.0,Ahvaz,Khuzestan,2024-06-11,Bronze,31,436.54,13532.74,82,Cash,iPhone,No,4,4
57,1058,Amir,F,47.0,Tehran,Tehran,2024-09-27,Bronze,5,151.81,759.05,336,Online Wallet,iPhone,No,0,2
58,1059,Ali,F,57.0,Isfahan,Isfahan,2023-09-05,Gold,31,287.05,8898.55,224,Online Wallet,iPhone,Yes,0,5
59,1060,Ali,M,63.0,Tabriz,East Azerbaijan,2021-04-27,Bronze,10,150.18,1501.80,236,Card,Web,Yes,7,3
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [13]:
df.describe()
#Descriptive statistics

,customer_id,age,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,61.000000,60.000000,61.000000,61.000000,60.000000,61.000000,61.000000,61.00000
mean,1030.229508,45.200000,17.606557,211.435738,3749.667333,196.934426,4.196721,3.00000
std,17.446483,19.167239,10.214824,130.113726,4262.248522,97.892436,2.663454,1.42595
min,1001.000000,19.000000,0.000000,27.630000,0.000000,3.000000,0.000000,1.00000
25%,1015.000000,31.750000,11.000000,108.190000,1167.035000,132.000000,2.000000,2.00000
50%,1030.000000,45.000000,17.000000,161.330000,2188.865000,201.000000,4.000000,3.00000
75%,1045.000000,58.000000,26.000000,323.320000,4692.150000,273.000000,7.000000,4.00000
max,1060.000000,145.000000,35.000000,449.810000,25000.000000,365.000000,8.000000,5.00000

In [20]:
# ─── Step 1: Duplicate Removal ───
df.duplicated(subset='customer_id').sum()
#Count duplicates by customer_id

df[df.duplicated(subset='customer_id', keep=False)]
#Show all duplicate rows

df = df.drop_duplicates(subset='customer_id', keep='first')
#Remove duplicates, keep first occurrence

df = df.reset_index(drop=True)
#Reset index from 0

print(df.shape)
#Verify new shape

print(df.duplicated(subset='customer_id').sum())
#Verify no duplicates remain

(60, 17)
0

In [21]:
print(f"Missing values per column:\n{df.isnull().sum()}")
#Count NaN per column

print(f"\nMissing percentages:\n{df.isnull().sum() / len(df) * 100}")
#Show NaN as percentage

print(f"\nRows with any missing value:\n{df[df.isnull().any(axis=1)]}")
#Show rows containing NaN

Missing values per column:
customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

Missing percentages:
customer_id           0.000000
first_name            0.000000
gender                0.000000
age                   1.666667
city                  0.000000
province              0.000000
signup_date           0.000000
membership_tier       0.000000
purchase_count        0.000000
avg_order_value       0.000000
total_spending        1.666667
last_purchase_days    0.000000
payment_method        0.000000
device                0.000000
discount_used         0.000000
returned_items        0.000000
satisfaction_score    0.000000
dtype: float64

Rows with any missing value:
    customer_id first_name gender   age     city province signup_date  \
19         1020      Kimia      M   NaN  Isfahan  Isfahan  2024-06-25
39         1040       Amir      F  65.0   Tehran   Tehran  2021-11-02

   membership_tier  purchase_count  avg_order_value  total_spending  \
19          Bronze              16           187.17         2994.72
39          Bronze              34            37.66             NaN

    last_purchase_days payment_method   device discount_used  returned_items  \
19                   4           Cash      Web           Yes               1
39                 126           Card  Android           Yes               3

    satisfaction_score
19                   5
39                   2

In [24]:
path = r"G:\Forough's Folders\StudyBuild\Project 01\cleaned_dataset.xlsx"
df.to_excel(path, index=False)
#Save to specific full path

In [25]:
# بررسی ناسازگاری قاعده total = count × avg
df['expected_total'] = df['purchase_count'] * df['avg_order_value']
#Calculate expected total based on the rule

df['diff'] = (df['total_spending'] - df['expected_total']).abs()
#Calculate absolute difference

df['rule_holds'] = df['diff'] < 1
#Check if the rule holds within 1 unit tolerance

print(f"Rows where rule holds: {df['rule_holds'].sum()} / {len(df)}")
#Count how many rows follow the rule

print(f"\nRows where rule is broken:")
print(df[~df['rule_holds']][['customer_id', 'purchase_count', 'avg_order_value', 
                              'total_spending', 'expected_total', 'diff']])
#Show rows where rule is violated

Rows where rule holds: 58 / 60

Rows where rule is broken:
    customer_id  purchase_count  avg_order_value  total_spending  \
29         1030              26           156.89         25000.0
39         1040              34            37.66             NaN

    expected_total      diff
29         4079.14  20920.86
39         1280.44       NaN

In [26]:
print(f"total_spending stats:\n{df['total_spending'].describe()}")
#Statistical summary of total_spending

print(f"\nRow 1030 details:")
print(df[df['customer_id'] == 1030].T)
#Show row 1030 transposed for readability

print(f"\nTop 5 highest total_spending:")
print(df.nlargest(5, 'total_spending')[['customer_id', 'purchase_count', 
                                        'avg_order_value', 'total_spending',
                                        'membership_tier']])
#Show top 5 rows by total_spending

total_spending stats:
count       59.000000
mean      3756.375424
std       4298.515563
min          0.000000
25%       1165.330000
50%       2140.380000
75%       4769.250000
max      25000.000000
Name: total_spending, dtype: float64

Row 1030 details:
                            29
customer_id               1030
first_name                Sina
gender                       M
age                       60.0
city                   Mashhad
province              Khorasan
signup_date         2025-03-07
membership_tier            VIP
purchase_count              26
avg_order_value         156.89
total_spending         25000.0
last_purchase_days         340
payment_method            Cash
device                     Web
discount_used              Yes
returned_items               4
satisfaction_score           4
expected_total         4079.14
diff                  20920.86
rule_holds               False

Top 5 highest total_spending:
    customer_id  purchase_count  avg_order_value  total_spending  \
29         1030              26           156.89        25000.00
43         1044              33           434.98        14354.34
56         1057              31           436.54        13532.74
11         1012              27           434.50        11731.50
8          1009              34           341.63        11615.42

   membership_tier
29             VIP
43            Gold
56          Bronze
11            Gold
8           Silver

In [31]:
# ─── IQR Method for Outlier Detection ───
Q1 = df['total_spending'].quantile(0.25)
#Calculate first quartile (25%)

Q3 = df['total_spending'].quantile(0.75)
#Calculate third quartile (75%)

IQR = Q3 - Q1
#Calculate interquartile range

lower_bound = Q1 - 1.5 * IQR
#Calculate lower bound

upper_bound = Q3 + 1.5 * IQR
#Calculate upper bound

print(f"Q1: {Q1:.2f}")
print(f"Q3: {Q3:.2f}")
print(f"IQR: {IQR:.2f}")
print(f"Lower Bound: {lower_bound:.2f}")
print(f"Upper Bound: {upper_bound:.2f}")
#Display all IQR metrics

outliers = df[(df['total_spending'] < lower_bound) | 
              (df['total_spending'] > upper_bound)].copy()
#Filter rows outside the bounds

outliers['expected_total'] = outliers['purchase_count'] * outliers['avg_order_value']
#Add expected_total column based on business rule

outliers['diff'] = (outliers['total_spending'] - outliers['expected_total']).abs()
#Calculate absolute difference from expected value

outliers['rule_holds'] = outliers['diff'] < 1
#Flag whether business rule holds (within 1 unit tolerance)

print(f"\nNumber of outliers: {len(outliers)}")
#Show count of outliers

# ─── Show outliers with RED highlighted total_spending ───
outliers[['customer_id', 'purchase_count', 'avg_order_value', 'expected_total',
          'total_spending', 'diff', 'rule_holds', 'membership_tier']].style \
    .map(lambda v: 'color: red; font-weight: bold', 
         subset=['total_spending']) \
    .format({'expected_total': '{:,.2f}', 
             'avg_order_value': '{:,.2f}',
             'total_spending': '{:,.2f}',
             'diff': '{:,.2f}'})
#Display outliers with total_spending in red and numbers formatted

Q1: 1165.33
Q3: 4769.25
IQR: 3603.92
Lower Bound: -4240.55
Upper Bound: 10175.13

Number of outliers: 5

In [32]:
# ─── Fix row 1030: invalid outlier (business rule violation) ───
df.loc[df['customer_id'] == 1030, 'total_spending'] = 4079.14
#Correct invalid value to expected (26 × 156.89)

# ─── Fix row 1040: impute NaN using business rule ───
df.loc[df['customer_id'] == 1040, 'total_spending'] = (
    df.loc[df['customer_id'] == 1040, 'purchase_count'].values[0] *
    df.loc[df['customer_id'] == 1040, 'avg_order_value'].values[0]
)
#Impute missing value with count × avg_order_value

# ─── Verification ───
print(f"Remaining NaN in total_spending: {df['total_spending'].isnull().sum()}")
#Verify no NaN remain

print(f"New Max: {df['total_spending'].max():.2f}")
#Verify 25000 is gone

print(f"New Mean: {df['total_spending'].mean():.2f}")
#Show new mean after fix

print(f"\nRow 1030 after fix:")
print(df[df['customer_id'] == 1030][['customer_id', 'purchase_count', 
                                      'avg_order_value', 'total_spending']])
#Verify row 1030 is corrected

print(f"\nRow 1040 after fix:")
print(df[df['customer_id'] == 1040][['customer_id', 'purchase_count', 
                                      'avg_order_value', 'total_spending']])
#Verify row 1040 is imputed

Remaining NaN in total_spending: 0
New Max: 14354.34
New Mean: 3366.43

Row 1030 after fix:
    customer_id  purchase_count  avg_order_value  total_spending
29         1030              26           156.89         4079.14

Row 1040 after fix:
    customer_id  purchase_count  avg_order_value  total_spending
39         1040              34            37.66         1280.44

In [33]:
# ─── Recalculate IQR after fixing ───
Q1_new = df['total_spending'].quantile(0.25)
Q3_new = df['total_spending'].quantile(0.75)
IQR_new = Q3_new - Q1_new

lower_new = Q1_new - 1.5 * IQR_new
upper_new = Q3_new + 1.5 * IQR_new

print(f"New Q1: {Q1_new:.2f}")
print(f"New Q3: {Q3_new:.2f}")
print(f"New IQR: {IQR_new:.2f}")
print(f"New Lower Bound: {lower_new:.2f}")
print(f"New Upper Bound: {upper_new:.2f}")

new_outliers = df[(df['total_spending'] < lower_new) | 
                  (df['total_spending'] > upper_new)]
print(f"\nRemaining outliers: {len(new_outliers)}")
print(new_outliers[['customer_id', 'total_spending', 'membership_tier']])
#Check remaining outliers after fixing

New Q1: 1167.04
New Q3: 4213.12
New IQR: 3046.08
New Lower Bound: -3402.09
New Upper Bound: 8782.24

Remaining outliers: 5
    customer_id  total_spending membership_tier
8          1009        11615.42          Silver
11         1012        11731.50            Gold
43         1044        14354.34            Gold
56         1057        13532.74          Bronze
58         1059         8898.55            Gold

In [34]:
# ─── Verify row 1059 follows the business rule ───
print("Row 1059 details:")
print(df[df['customer_id'] == 1059][['customer_id', 'purchase_count', 
                                      'avg_order_value', 'total_spending']])
#Inspect row 1059

expected_1059 = df.loc[df['customer_id'] == 1059, 'purchase_count'].values[0] * \
                df.loc[df['customer_id'] == 1059, 'avg_order_value'].values[0]
print(f"\nExpected for 1059: {expected_1059:.2f}")
print(f"Actual for 1059: {df.loc[df['customer_id'] == 1059, 'total_spending'].values[0]:.2f}")
print(f"Rule holds: {abs(expected_1059 - df.loc[df['customer_id'] == 1059, 'total_spending'].values[0]) < 1}")
#Verify business rule for row 1059

Row 1059 details:
    customer_id  purchase_count  avg_order_value  total_spending
58         1059              31           287.05         8898.55

Expected for 1059: 8898.55
Actual for 1059: 8898.55
Rule holds: True

In [35]:
# ─── Check current data types ───
print(df.dtypes)
#Show current data types of all columns

print(f"\nDetailed info:")
df.info()
#Show detailed info including non-null counts

print(f"\nMemory usage: {df.memory_usage(deep=True).sum() / 1024:.2f} KB")
#Check memory usage

customer_id             int64
first_name                str
gender                    str
age                   float64
city                      str
province                  str
signup_date               str
membership_tier           str
purchase_count          int64
avg_order_value       float64
total_spending        float64
last_purchase_days      int64
payment_method            str
device                    str
discount_used             str
returned_items          int64
satisfaction_score      int64
expected_total        float64
diff                  float64
rule_holds               bool
dtype: object

Detailed info:
<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         60 non-null     int64
 1   first_name          60 non-null     str
 2   gender              60 non-null     str
 3   age                 59 non-null     float64
 4   city                60 non-null     str
 5   province            60 non-null     str
 6   signup_date         60 non-null     str
 7   membership_tier     60 non-null     str
 8   purchase_count      60 non-null     int64
 9   avg_order_value     60 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  60 non-null     int64
 12  payment_method      60 non-null     str
 13  device              60 non-null     str
 14  discount_used       60 non-null     str
 15  returned_items      60 non-null     int64
 16  satisfaction_score  60 non-null     int64
 17  expected_total      60 non-null     float64
 18  diff                59 non-null     float64
 19  rule_holds          60 non-null     bool
dtypes: bool(1), float64(5), int64(5), str(9)
memory usage: 12.1 KB

Memory usage: 12.06 KB

In [39]:
# ─── Step 2a: Drop helper columns (if exist) ───
helper_cols = ['expected_total', 'diff', 'rule_holds']
#List helper columns to remove

cols_to_drop = [c for c in helper_cols if c in df.columns]
#Filter only those that actually exist

if cols_to_drop:
    df = df.drop(columns=cols_to_drop)
    print(f"Dropped: {cols_to_drop}")
else:
    print("No helper columns to drop")
#Drop only existing columns

print(f"\nShape after dropping: {df.shape}")
#Verify dimensions

print(f"Columns now ({len(df.columns)}): {list(df.columns)}")
#List remaining columns

No helper columns to drop

Shape after dropping: (60, 17)
Columns now (17): ['customer_id', 'first_name', 'gender', 'age', 'city', 'province', 'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value', 'total_spending', 'last_purchase_days', 'payment_method', 'device', 'discount_used', 'returned_items', 'satisfaction_score']

In [40]:
# ─── Step 2b: Convert signup_date to datetime ───
df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')
#Convert string dates to datetime objects

print(f"signup_date dtype: {df['signup_date'].dtype}")
#Verify conversion

print(f"signup_date range: {df['signup_date'].min()} to {df['signup_date'].max()}")
#Check date range

print(f"Any failed conversions (NaT): {df['signup_date'].isnull().sum()}")
#Check if any dates failed to parse

print(f"\nFirst 5 rows of signup_date:")
print(df['signup_date'].head())
#Preview converted dates

signup_date dtype: datetime64[us]
signup_date range: 2021-02-23 00:00:00 to 2025-09-09 00:00:00
Any failed conversions (NaT): 0

First 5 rows of signup_date:
0   2025-02-19
1   2022-08-19
2   2023-06-20
3   2021-11-08
4   2021-10-21
Name: signup_date, dtype: datetime64[us]

In [41]:
# ─── Step 2c: Convert age to nullable Int64 ───
print(f"Before: dtype = {df['age'].dtype}")
#Check current dtype

print(f"Before: sample = {df['age'].head(3).tolist()}")
#Show sample values (note the .0)

df['age'] = df['age'].astype('Int64')
#Convert to nullable integer

print(f"\nAfter: dtype = {df['age'].dtype}")
#Verify new dtype

print(f"After: sample = {df['age'].head(3).tolist()}")
#Show sample values (no .0)

print(f"\nMissing values in age: {df['age'].isnull().sum()}")
#Verify NaN is preserved

Before: dtype = float64
Before: sample = [19.0, 53.0, 31.0]

After: dtype = Int64
After: sample = [19, 53, 31]

Missing values in age: 1

In [42]:
# ─── Step 2d: Convert discount_used to boolean ───
print(f"Before: {df['discount_used'].unique()}")
#Show unique values before conversion

df['discount_used'] = df['discount_used'].map({'Yes': True, 'No': False})
#Map Yes/No to True/False

print(f"After: {df['discount_used'].unique()}")
#Show unique values after conversion

print(f"dtype: {df['discount_used'].dtype}")
#Verify boolean dtype

print(f"\nCount of True: {df['discount_used'].sum()}")
#Count how many customers used discount

Before: <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
After: [ True False]
dtype: bool

Count of True: 26

In [43]:
# ─── Step 2e: Convert nominal columns to category ───
nominal_cols = ['gender', 'city', 'province', 'payment_method', 'device']
#List of nominal columns

print("Before:")
for col in nominal_cols:
    print(f"  {col}: {df[col].dtype} | unique: {df[col].nunique()}")
#Show dtypes and unique counts before

for col in nominal_cols:
    df[col] = df[col].astype('category')
#Convert each nominal column to category

print("\nAfter:")
for col in nominal_cols:
    print(f"  {col}: {df[col].dtype} | unique: {df[col].nunique()}")
#Show dtypes after conversion

print(f"\nMemory usage: {df.memory_usage(deep=True).sum() / 1024:.2f} KB")
#Check total memory usage

Before:
  gender: str | unique: 2
  city: str | unique: 8
  province: str | unique: 8
  payment_method: str | unique: 3
  device: str | unique: 3

After:
  gender: category | unique: 2
  city: category | unique: 8
  province: category | unique: 8
  payment_method: category | unique: 3
  device: category | unique: 3

Memory usage: 6.57 KB

In [44]:
# ─── Step 2f: Convert membership_tier to ordered category ───
from pandas.api.types import CategoricalDtype
#Import CategoricalDtype for custom ordering

print(f"Before: {df['membership_tier'].dtype}")
print(f"Values: {df['membership_tier'].unique()}")
#Show current state

tier_order = CategoricalDtype(
    categories=['Bronze', 'Silver', 'Gold', 'VIP'],
    ordered=True
)
#Define the correct hierarchy

df['membership_tier'] = df['membership_tier'].astype(tier_order)
#Convert to ordered category

print(f"\nAfter: {df['membership_tier'].dtype}")
print(f"Order: {df['membership_tier'].cat.categories.tolist()}")
#Show the defined order

print(f"\nTest sorting by tier:")
print(df.sort_values('membership_tier')['membership_tier'].head(10).tolist())
#Verify sorting follows hierarchy

Before: str
Values: <ArrowStringArray>
['VIP', 'Gold', 'Silver', 'Bronze']
Length: 4, dtype: str

After: category
Order: ['Bronze', 'Silver', 'Gold', 'VIP']

Test sorting by tier:
['Bronze', 'Bronze', 'Bronze', 'Bronze', 'Bronze', 'Bronze', 'Bronze', 'Bronze', 'Bronze', 'Bronze']

In [46]:
# ─── Final dtype verification ───
print("Final data types:")
print(df.dtypes)
#Show all column dtypes

print(f"\nDetailed info:")
df.info()
#Show detailed info

print(f"\nShape: {df.shape}")
#Verify dimensions

print(f"\nMissing values:")
print(df.isnull().sum())
#Verify missing values

print(f"\nDuplicates: {df.duplicated(subset='customer_id').sum()}")
#Verify no duplicates

Final data types:
customer_id                    int64
first_name                       str
gender                      category
age                            Int64
city                        category
province                    category
signup_date           datetime64[us]
membership_tier             category
purchase_count                 int64
avg_order_value              float64
total_spending               float64
last_purchase_days             int64
payment_method              category
device                      category
discount_used                   bool
returned_items                 int64
satisfaction_score             int64
dtype: object

Detailed info:
<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         60 non-null     int64
 1   first_name          60 non-null     str
 2   gender              60 non-null     category
 3   age                 59 non-null     Int64
 4   city                60 non-null     category
 5   province            60 non-null     category
 6   signup_date         60 non-null     datetime64[us]
 7   membership_tier     60 non-null     category
 8   purchase_count      60 non-null     int64
 9   avg_order_value     60 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  60 non-null     int64
 12  payment_method      60 non-null     category
 13  device              60 non-null     category
 14  discount_used       60 non-null     bool
 15  returned_items      60 non-null     int64
 16  satisfaction_score  60 non-null     int64
dtypes: Int64(1), bool(1), category(6), datetime64[us](1), float64(2), int64(5), str(1)
memory usage: 6.1 KB

Shape: (60, 17)

Missing values:
customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

Duplicates: 0

In [48]:
# ─── Save cleaned dataset ───
df.to_excel('cleaned_dataset_githubusername.xlsx', index=False)
#Save final cleaned dataset to Excel

print("Dataset saved successfully!")
#Confirm save

# ─── Verify by reloading ───
df_check = pd.read_excel('cleaned_dataset_githubusername.xlsx')
#Reload the saved file

print(f"\nReloaded shape: {df_check.shape}")
#Verify dimensions

print(f"Reloaded dtypes:")
print(df_check.dtypes)
#Verify dtypes persisted

Dataset saved successfully!

Reloaded shape: (60, 17)
Reloaded dtypes:
customer_id                    int64
first_name                       str
gender                           str
age                          float64
city                             str
province                         str
signup_date           datetime64[us]
membership_tier                  str
purchase_count                 int64
avg_order_value              float64
total_spending               float64
last_purchase_days             int64
payment_method                   str
device                           str
discount_used                   bool
returned_items                 int64
satisfaction_score             int64
dtype: object

In [49]:
df.to_pickle('cleaned_dataset_username.pkl')
#Save with exact dtypes preserved (optional)

df_pickle = pd.read_pickle('cleaned_dataset_username.pkl')
print(df_pickle.dtypes)
#Verify dtypes are preserved

customer_id                    int64
first_name                       str
gender                      category
age                            Int64
city                        category
province                    category
signup_date           datetime64[us]
membership_tier             category
purchase_count                 int64
avg_order_value              float64
total_spending               float64
last_purchase_days             int64
payment_method              category
device                      category
discount_used                   bool
returned_items                 int64
satisfaction_score             int64
dtype: object

In [50]:
# ─── Quick consistency checks ───
print("1. Returned > purchased:")
print(df[df['returned_items'] > df['purchase_count']].shape[0], "rows")

print("\n2. Zero spending with purchases:")
print(df[(df['total_spending'] == 0) & (df['purchase_count'] > 0)].shape[0], "rows")

print("\n3. Future signup dates:")
print(df[df['signup_date'] > pd.Timestamp.today()].shape[0], "rows")

print("\n4. Age range:")
print(f"  min: {df['age'].min()}, max: {df['age'].max()}")

print("\n5. Satisfaction range:")
print(f"  min: {df['satisfaction_score'].min()}, max: {df['satisfaction_score'].max()}")

1. Returned > purchased:
6 rows

2. Zero spending with purchases:
0 rows

3. Future signup dates:
0 rows

4. Age range:
  min: 19, max: 145

5. Satisfaction range:
  min: 1, max: 5

In [51]:
# ─── Check rows with returned > purchased ───
problem_rows = df[df['returned_items'] > df['purchase_count']]
print(f"Rows with returned > purchased: {len(problem_rows)}")
print(problem_rows[['customer_id', 'purchase_count', 'returned_items', 
                     'total_spending', 'satisfaction_score']])
#Show all rows with the issue

print(f"\nDifference (returned - purchased):")
print((problem_rows['returned_items'] - problem_rows['purchase_count']).tolist())
#Show how much they exceed

Rows with returned > purchased: 6
    customer_id  purchase_count  returned_items  total_spending  \
7          1008               3               8         1168.74
14         1015               3               8          923.73
23         1024               0               2            0.00
28         1029               2               4          646.64
36         1037               1               7          387.68
55         1056               1               4          449.81

    satisfaction_score
7                    1
14                   4
23                   1
28                   5
36                   2
55                   2

Difference (returned - purchased):
[5, 5, 2, 2, 6, 3]

In [53]:
# ─── Check age outliers ───
print(df[df['age'] > 100][['customer_id', 'first_name', 'age']])
#Show rows with unrealistic age

# ─── Fix unrealistic age ───
print(f"Before: age max = {df['age'].max()}")

df.loc[df['age'] > 100, 'age'] = pd.NA
#Replace unrealistic ages (>100) with NA

print(f"After: age max = {df['age'].max()}")
print(f"Missing ages now: {df['age'].isnull().sum()}")
#Verify fix

print(f"\nRows with missing age:")
print(df[df['age'].isnull()][['customer_id', 'first_name', 'age']])
#Show rows with missing age

   customer_id first_name  age
9         1010      Arash  145
Before: age max = 145
After: age max = 65
Missing ages now: 2

Rows with missing age:
    customer_id first_name   age
9          1010      Arash  <NA>
19         1020      Kimia  <NA>

In [55]:
# ─── Save final cleaned dataset ───
df.to_excel('cleaned_dataset_forough-shafiepour.xlsx', index=False)
#Save with GitHub username

print(f"Final shape: {df.shape}")
print(f"Final missing values: {df.isnull().sum().sum()}")
print(f"Dataset saved as: cleaned_dataset_forough-shafiepour.xlsx")

Final shape: (60, 17)
Final missing values: 2
Dataset saved as: cleaned_dataset_forough-shafiepour.xlsx